language: python

matrix:
  include:
    - os: osx
      before_install:
        - pip install pipenv
        - brew install git-lfs

    - os: linux
      dst: xenial
      before_install:
        - pip install pipenv

    - os: linux
      dst: bionic
      before_install:
        - pip install pipenv

install: pipenv install --dev

before_script:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull

script:
  - make test
