language: python
python: "3.7"
cache:
  directories:
    - faceDetection/learned-models
    - $HOME/.local/share/virtualenvs

dst:
  - xenial
  - bionic

before_install: pip install pipenv

install: travis_wait 25 pipenv install --dev

before_script:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull

script:
  - pipenv run test
  - pipenv run lint
