#!/usr/bin/env bash
#
# Face-data-server wrapper script
#
#
# Copyright 2018 (c) Cj-bc
# This software is released under MIT License
#
# @(#) version -

cd ${BASH_SOURCE[0]%/*}
which pipenv >/dev/null 2>&1 || return 1
pipenv run python main.py "$@"
