# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import faceDataServer_pb2 as faceDataServer__pb2


class FaceDataServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.streamData = channel.stream_stream(
        '/FaceDataServer/streamData',
        request_serializer=faceDataServer__pb2.ReqCommand.SerializeToString,
        response_deserializer=faceDataServer__pb2.FaceData.FromString,
        )


class FaceDataServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def streamData(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FaceDataServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'streamData': grpc.stream_stream_rpc_method_handler(
          servicer.streamData,
          request_deserializer=faceDataServer__pb2.ReqCommand.FromString,
          response_serializer=faceDataServer__pb2.FaceData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FaceDataServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
