# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faceDataServer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='faceDataServer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x66\x61\x63\x65\x44\x61taServer.proto\"2\n\nReqCommand\"$\n\x03msg\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01\x12\x08\n\x04\x45XIT\x10\x02\"+\n\x08\x46\x61\x63\x65\x44\x61ta\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x32<\n\x0e\x46\x61\x63\x65\x44\x61taServer\x12*\n\nstreamData\x12\x0b.ReqCommand\x1a\t.FaceData\"\x00(\x01\x30\x01\x62\x06proto3')
)



_REQCOMMAND_MSG = _descriptor.EnumDescriptor(
  name='msg',
  full_name='ReqCommand.msg',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXIT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=38,
  serialized_end=74,
)
_sym_db.RegisterEnumDescriptor(_REQCOMMAND_MSG)


_REQCOMMAND = _descriptor.Descriptor(
  name='ReqCommand',
  full_name='ReqCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQCOMMAND_MSG,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=74,
)


_FACEDATA = _descriptor.Descriptor(
  name='FaceData',
  full_name='FaceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='FaceData.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='FaceData.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='FaceData.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=119,
)

_REQCOMMAND_MSG.containing_type = _REQCOMMAND
DESCRIPTOR.message_types_by_name['ReqCommand'] = _REQCOMMAND
DESCRIPTOR.message_types_by_name['FaceData'] = _FACEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqCommand = _reflection.GeneratedProtocolMessageType('ReqCommand', (_message.Message,), {
  'DESCRIPTOR' : _REQCOMMAND,
  '__module__' : 'faceDataServer_pb2'
  # @@protoc_insertion_point(class_scope:ReqCommand)
  })
_sym_db.RegisterMessage(ReqCommand)

FaceData = _reflection.GeneratedProtocolMessageType('FaceData', (_message.Message,), {
  'DESCRIPTOR' : _FACEDATA,
  '__module__' : 'faceDataServer_pb2'
  # @@protoc_insertion_point(class_scope:FaceData)
  })
_sym_db.RegisterMessage(FaceData)



_FACEDATASERVER = _descriptor.ServiceDescriptor(
  name='FaceDataServer',
  full_name='FaceDataServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=121,
  serialized_end=181,
  methods=[
  _descriptor.MethodDescriptor(
    name='streamData',
    full_name='FaceDataServer.streamData',
    index=0,
    containing_service=None,
    input_type=_REQCOMMAND,
    output_type=_FACEDATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACEDATASERVER)

DESCRIPTOR.services_by_name['FaceDataServer'] = _FACEDATASERVER

# @@protoc_insertion_point(module_scope)
