# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faceDataServer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='faceDataServer.proto',
  package='FaceDataServer',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x66\x61\x63\x65\x44\x61taServer.proto\x12\x0e\x46\x61\x63\x65\x44\x61taServer\"\t\n\x07VoidCom\"\x16\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\"Q\n\x06Status\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x65xitCode\x18\x02 \x01(\x05\x12$\n\x05token\x18\x03 \x01(\x0b\x32\x15.FaceDataServer.Token\"+\n\x08\x46\x61\x63\x65\x44\x61ta\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x32\x8d\x02\n\x0e\x46\x61\x63\x65\x44\x61taServer\x12\x39\n\x04init\x12\x17.FaceDataServer.VoidCom\x1a\x16.FaceDataServer.Status\"\x00\x12\x42\n\x0bstartStream\x12\x15.FaceDataServer.Token\x1a\x18.FaceDataServer.FaceData\"\x00\x30\x01\x12=\n\nstopStream\x12\x15.FaceDataServer.Token\x1a\x16.FaceDataServer.Status\"\x00\x12=\n\x08shutdown\x12\x17.FaceDataServer.VoidCom\x1a\x16.FaceDataServer.Status\"\x00\x62\x06proto3')
)




_VOIDCOM = _descriptor.Descriptor(
  name='VoidCom',
  full_name='FaceDataServer.VoidCom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=49,
)


_TOKEN = _descriptor.Descriptor(
  name='Token',
  full_name='FaceDataServer.Token',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='FaceDataServer.Token.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=73,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='FaceDataServer.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='FaceDataServer.Status.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exitCode', full_name='FaceDataServer.Status.exitCode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='FaceDataServer.Status.token', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=156,
)


_FACEDATA = _descriptor.Descriptor(
  name='FaceData',
  full_name='FaceDataServer.FaceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='FaceDataServer.FaceData.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='FaceDataServer.FaceData.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='FaceDataServer.FaceData.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=201,
)

_STATUS.fields_by_name['token'].message_type = _TOKEN
DESCRIPTOR.message_types_by_name['VoidCom'] = _VOIDCOM
DESCRIPTOR.message_types_by_name['Token'] = _TOKEN
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['FaceData'] = _FACEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VoidCom = _reflection.GeneratedProtocolMessageType('VoidCom', (_message.Message,), {
  'DESCRIPTOR' : _VOIDCOM,
  '__module__' : 'faceDataServer_pb2'
  # @@protoc_insertion_point(class_scope:FaceDataServer.VoidCom)
  })
_sym_db.RegisterMessage(VoidCom)

Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), {
  'DESCRIPTOR' : _TOKEN,
  '__module__' : 'faceDataServer_pb2'
  # @@protoc_insertion_point(class_scope:FaceDataServer.Token)
  })
_sym_db.RegisterMessage(Token)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'faceDataServer_pb2'
  # @@protoc_insertion_point(class_scope:FaceDataServer.Status)
  })
_sym_db.RegisterMessage(Status)

FaceData = _reflection.GeneratedProtocolMessageType('FaceData', (_message.Message,), {
  'DESCRIPTOR' : _FACEDATA,
  '__module__' : 'faceDataServer_pb2'
  # @@protoc_insertion_point(class_scope:FaceDataServer.FaceData)
  })
_sym_db.RegisterMessage(FaceData)



_FACEDATASERVER = _descriptor.ServiceDescriptor(
  name='FaceDataServer',
  full_name='FaceDataServer.FaceDataServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=204,
  serialized_end=473,
  methods=[
  _descriptor.MethodDescriptor(
    name='init',
    full_name='FaceDataServer.FaceDataServer.init',
    index=0,
    containing_service=None,
    input_type=_VOIDCOM,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='startStream',
    full_name='FaceDataServer.FaceDataServer.startStream',
    index=1,
    containing_service=None,
    input_type=_TOKEN,
    output_type=_FACEDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stopStream',
    full_name='FaceDataServer.FaceDataServer.stopStream',
    index=2,
    containing_service=None,
    input_type=_TOKEN,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='shutdown',
    full_name='FaceDataServer.FaceDataServer.shutdown',
    index=3,
    containing_service=None,
    input_type=_VOIDCOM,
    output_type=_STATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACEDATASERVER)

DESCRIPTOR.services_by_name['FaceDataServer'] = _FACEDATASERVER

# @@protoc_insertion_point(module_scope)
