# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faceDataServer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='faceDataServer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x66\x61\x63\x65\x44\x61taServer.proto\"\t\n\x07VoidCom\"+\n\x06Status\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x65xitCode\x18\x02 \x01(\x05\"2\n\nReqCommand\"$\n\x03msg\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01\x12\x08\n\x04\x45XIT\x10\x02\"+\n\x08\x46\x61\x63\x65\x44\x61ta\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x32{\n\x0e\x46\x61\x63\x65\x44\x61taServer\x12\x1b\n\x04init\x12\x08.VoidCom\x1a\x07.Status\"\x00\x12)\n\x0bstartStream\x12\x0b.ReqCommand\x1a\t.FaceData\"\x00\x30\x01\x12!\n\nstopStream\x12\x08.VoidCom\x1a\x07.Status\"\x00\x62\x06proto3')
)



_REQCOMMAND_MSG = _descriptor.EnumDescriptor(
  name='msg',
  full_name='ReqCommand.msg',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXIT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=94,
  serialized_end=130,
)
_sym_db.RegisterEnumDescriptor(_REQCOMMAND_MSG)


_VOIDCOM = _descriptor.Descriptor(
  name='VoidCom',
  full_name='VoidCom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=33,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='Status.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exitCode', full_name='Status.exitCode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=78,
)


_REQCOMMAND = _descriptor.Descriptor(
  name='ReqCommand',
  full_name='ReqCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQCOMMAND_MSG,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=130,
)


_FACEDATA = _descriptor.Descriptor(
  name='FaceData',
  full_name='FaceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='FaceData.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='FaceData.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='FaceData.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=175,
)

_REQCOMMAND_MSG.containing_type = _REQCOMMAND
DESCRIPTOR.message_types_by_name['VoidCom'] = _VOIDCOM
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['ReqCommand'] = _REQCOMMAND
DESCRIPTOR.message_types_by_name['FaceData'] = _FACEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VoidCom = _reflection.GeneratedProtocolMessageType('VoidCom', (_message.Message,), {
  'DESCRIPTOR' : _VOIDCOM,
  '__module__' : 'faceDataServer_pb2'
  # @@protoc_insertion_point(class_scope:VoidCom)
  })
_sym_db.RegisterMessage(VoidCom)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'faceDataServer_pb2'
  # @@protoc_insertion_point(class_scope:Status)
  })
_sym_db.RegisterMessage(Status)

ReqCommand = _reflection.GeneratedProtocolMessageType('ReqCommand', (_message.Message,), {
  'DESCRIPTOR' : _REQCOMMAND,
  '__module__' : 'faceDataServer_pb2'
  # @@protoc_insertion_point(class_scope:ReqCommand)
  })
_sym_db.RegisterMessage(ReqCommand)

FaceData = _reflection.GeneratedProtocolMessageType('FaceData', (_message.Message,), {
  'DESCRIPTOR' : _FACEDATA,
  '__module__' : 'faceDataServer_pb2'
  # @@protoc_insertion_point(class_scope:FaceData)
  })
_sym_db.RegisterMessage(FaceData)



_FACEDATASERVER = _descriptor.ServiceDescriptor(
  name='FaceDataServer',
  full_name='FaceDataServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=177,
  serialized_end=300,
  methods=[
  _descriptor.MethodDescriptor(
    name='init',
    full_name='FaceDataServer.init',
    index=0,
    containing_service=None,
    input_type=_VOIDCOM,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='startStream',
    full_name='FaceDataServer.startStream',
    index=1,
    containing_service=None,
    input_type=_REQCOMMAND,
    output_type=_FACEDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stopStream',
    full_name='FaceDataServer.stopStream',
    index=2,
    containing_service=None,
    input_type=_VOIDCOM,
    output_type=_STATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACEDATASERVER)

DESCRIPTOR.services_by_name['FaceDataServer'] = _FACEDATASERVER

# @@protoc_insertion_point(module_scope)
